name: Check

on:
  workflow_dispatch:

  push:
    branches: [develop]

jobs:

  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install black flake8 isort
      - run: black --version
      - run: isort --check .
      - run: black --check .
      - run: flake8 .

  checks:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-20.04"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install etcd
        run: |
          ETCD_VER=v3.4.14
          DOWNLOAD_URL=https://github.com/etcd-io/etcd/releases/download
          curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
          mkdir /tmp/etcd-download-test
          tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1
          /tmp/etcd-download-test/etcd &

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .
          pip install -e aviso-server/monitoring
          pip install -e aviso-server/rest
          pip install -e aviso-server/auth
          pip install -e aviso-server/admin
          pip install -U -r tests/requirements-dev.txt
          pip install -r docs/requirements.txt

      - name: Tests
        run: |
          pytest -v --cov=pyaviso --cache-clear
        env:
          AVISO_DEBUG: True
      - name: Documentation
        run: |
          make clean
          make html
        working-directory: docs